name: news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
